---
all:
  application.addons:
    type: "string"
    default: "-"
    description: >-
      Comma-separated list of addons that every application managed by
      AMS will use. See
      [How to enable an addon globally](https://discourse.ubuntu.com/t/enable-an-addon-globally/25285).
    deprecated: "No"  # Unquoted No will be considered as false in YAML parsing
  application.auto_publish:
    type: "bool"
    default: "true"
    description: >-
      If set to `true`, AMS automatically published new application
      versions when the bootstrap process is finished. `false`
      disables this. See
      [Publish application versions](https://discourse.ubuntu.com/t/update-an-application/24201#publish-application-versions-1).
    deprecated: "No"
  application.auto_update:
    type: "bool"
    default: "true"
    description: >-
      If set to `true`, AMS automatically updates applications
      whenever any dependencies (parent image, addons, global
      configuration) change. `false` disables this. See
      [Configure automatic application updates](https://discourse.ubuntu.com/t/update-an-application/24201#configure-automatic-application-updates-3).
    deprecated: "No"
  application.default_abi:
    type: "string"
    default: "-"
    description: >-
      Default Android ABI that applications should use. See
      [Android ABIs](https://developer.android.com/ndk/guides/abis)
      for a list of available ABIs.
    deprecated: "No"
  application.max_published_versions:
    type: "integer"
    default: "3"
    description: >-
      Maximum number of published versions per application. If the
      number of versions of an application exceeds this configuration,
      AMS will automatically clean up older versions.
    deprecated: "No"
  container.apt_mirror:
    type: "string"
    default: "-"
    description: >-
      APT mirror to use within the containers. By default,
      `http://archive.ubuntu.com` (amd64) or `http://ports.ubuntu.com`
      (arm64) is used. This configuration item is deprecated since 1.20,
      use `instance.apt_mirror` instead.
    deprecated: "Yes"
  instance.apt_mirror:
    type: "string"
    default: "-"
    description: >-
      APT mirror to use within the instances. By default,
      `http://archive.ubuntu.com` (amd64) or `http://ports.ubuntu.com`
      (arm64) is used.
    deprecated: "No"
  container.default_platform:
    type: "string"
    default: "-"
    description: >-
      The name of the platform that Anbox Cloud uses by default to launch
      containers. This configuration item is deprecated since 1.20,
      use `instance.default_platform` instead.
    deprecated: "Yes"
  instance.default_platform:
    type: "string"
    default: "-"
    description: >-
      The name of the platform that Anbox Cloud uses by default to launch
      instances.
    deprecated: "No"
  container.features:
    type: "string"
    default: "-"
    description: >-
      Comma-separated list of features to enable (see list below).
      This configuration item is deprecated since 1.20, use
      `instance.features` instead.
    deprecated: "Yes"
  instance.features:
    type: "string"
    default: "-"
    description: >-
      Comma-separated list of features to enable (see list below).
    deprecated: "No"
  container.network_proxy:
    type: "string"
    default: "-"
    description: >-
      Network proxy to use inside the containers. This configuration
      item is deprecated since 1.20, use `instance.network_proxy`
      instead.
    deprecated: "Yes"
  instance.network_proxy:
    type: "string"
    default: "-"
    description: >-
      Network proxy to use inside the instances.
    deprecated: "No"
  container.security_updates:
    type: "bool"
    default: "true"
    description: >-
      If set to `true`, automatic Ubuntu security updates are applied
      during the application bootstrap process. `false` disables this.
    deprecated: "Yes"
  instance.security_updates:
    type: "bool"
    default: "true"
    description: >-
      If set to `true`, automatic Ubuntu security updates are applied
      during the application bootstrap process. `false` disables this.
      This configuration item is deprecated since 1.20, use
      `instance.security_updates` instead.
    deprecated: "No"
  core.proxy_http:
    type: "string"
    default: "-"
    description: >-
      HTTP proxy to use for HTTP requests that AMS performs.
    deprecated: "No"
  core.proxy_https:
    type: "string"
    default: "-"
    description: >-
      HTTPS proxy to use for HTTPS requests that AMS performs.
    deprecated: "No"
  core.proxy_ignore_hosts:
    type: "string"
    default: "-"
    description: >-
      Comma-separated list that defines the hosts for which a
      configured proxy is not used.
    deprecated: "No"
  core.trust_password:
    type: "string"
    default: "-"
    description: >-
      The AMS trust password.
    deprecated: "No"
  cpu.limit_mode:
    type: "string"
    default: "scheduler"
    description: >-
      The mode AMS uses to limit CPU access for an instance. See
      [About performance](https://discourse.ubuntu.com/t/about-performance/29416) for details.
      Possible values are: `scheduler`, `pinning`
    deprecated: "No"
  gpu.allocation_mode:
    type: "string"
    default: "`all`"
    description: >-
      Method of allocating GPUs: `all` tells AMS to allocate all
      available GPUs on a system to an instance. `single` allocates
      only a single GPU.
    deprecated: "No"
  gpu.type:
    type: "string"
    default: "`none`"
    description: >-
      Type of GPU: `none`, `intel`, `nvidia`, `amd`
    deprecated: "No"
  images.allow_insecure:
    type: "bool"
    default: "false"
    description: >-
      If set to `true`, AMS allows accepting untrusted certificates
      provided by the configured image server.
    deprecated: "No"
  images.auth:
    type: "string"
    default: "-"
    description: >-
      Authentication details for AMS to access the image server. When
      reading this configuration, a Boolean value that indicates
      whether the item is set is returned, to avoid exposing
      credentials.
    deprecated: "No"
  images.update_interval:
    type: "string"
    default: "`5m`"
    description: >-
      Frequency of image updates (for example: 1h, 30m).
    deprecated: "No"
  images.url:
    type: "string"
    default: "`https://images.anbox-cloud.io/stable/`"
    description: >-
      URL of the image server to use.
    deprecated: "No"
  images.version_lockstep:
    type: "bool"
    default: "true"
    description: >-
      Whether to put the version of the latest pulled image and the
      AMS version in a lockstep. This ensures that a deployment is not
      automatically updated to newer image versions if AMS is still at
      an older version. This only applies for new major and minor but
      not patch version updates.
    deprecated: "No"
  load_balancer.url:
    type: "string"
    default: "-"
    description: >-
      URL of the load balancer behind which AMS sits. The URL is
      handed to instances started by AMS to allow them to contact AMS
      through the load balancer and not via the address of an
      individual AMS instance.
    deprecated: "No"
  node.queue_size:
    type: "integer"
    default: "100"
    description: >-
      Maximum size of the queue containing requests to start and stop
      instances per LXD node. Changing the value requires a restart of
      AMS.
    deprecated: "No"
  node.workers_per_queue:
    type: "integer"
    default: "4"
    description: >-
      Number of workers processing instance start and stop requests.
      Changing the value requires a restart of AMS.
    deprecated: "No"
  registry.filter:
    type: "string"
    default: "-"
    description: >-
      Comma-separated list of tags to filter for when applications are
      fetched from the
      [Anbox Application Registry](https://discourse.ubuntu.com/t/application-registry/17761).
      If empty, no filter is applied.
    deprecated: "No"
  registry.fingerprint:
    type: "string"
    default: "-"
    description: >-
      Fingerprint of the certificate that the
      [Anbox Application Registry](https://discourse.ubuntu.com/t/application-registry/17761)
      uses to TLS-secure its HTTPS endpoint. This is used by AMS for
      mutual TLS authentication with the registry.
    deprecated: "No"
  registry.mode:
    type: "string"
    default: "`pull`"
    description: >-
      Mode in which the
      [Anbox Application Registry](https://discourse.ubuntu.com/t/application-registry/17761)
      client in AMS operates: `manual`, `pull`, `push`
    deprecated: "No"
  registry.update_interval:
    type: "string"
    default: "`1h`"
    description: >-
      Frequency of
      [Anbox Application Registry](https://discourse.ubuntu.com/t/application-registry/17761)
      updates (for example: 1h, 30m).
    deprecated: "No"
  registry.url:
    type: "string"
    default: "-"
    description: >-
      URL of the
      [Anbox Application Registry](https://discourse.ubuntu.com/t/application-registry/17761)
      to use.
    deprecated: "No"
  scheduler.strategy:
    type: "string"
    default: "`spread`"
    description: >-
      Strategy that the internal instance scheduler in AMS uses to
      distribute instances across available LXD nodes: `binpack`,
      `spread`
    deprecated: "No"
node:
  cpu-allocation-rate:
    type: "integer"
    default: "4"
    description: >-
      CPU allocation rate used for
      [over-committing resources](https://discourse.ubuntu.com/t/about-capacity-planning/28717#over-committing-resources-3).
    deprecated: "No"
  cpus:
    type: "integer"
    default: "all available"
    description: >-
      Number of CPUs dedicated to instances.
    deprecated: "No"
  gpu-encoder-slots:
    type: "integer"
    default: >-
      0 (for nodes without GPU or with AMD GPU)<br/>32 (for nodes with
      NVIDIA GPU)<br/>10 (for nodes with Intel GPU)
    description: >-
      Number of GPU encoder slots available on the node.
    deprecated: "No"
  gpu-slots:
    type: "integer"
    default: >-
      0 (for nodes without GPU)<br/>32 (for nodes with NVIDIA
      GPU)<br/>10 (for nodes with AMD or Intel GPU)
    description: >-
      Number of
      [GPU slots](https://discourse.ubuntu.com/t/about-capacity-planning/28717#gpu-slots-2)
      available on the node.
    deprecated: "No"
  memory:
    type: "integer"
    default: "all available"
    description: >-
      Memory dedicated to instances.
    deprecated: "No"
  memory-allocation-rate:
    type: "integer"
    default: "2"
    description: >-
      Memory allocation rate used for
      [over-committing resources](https://discourse.ubuntu.com/t/about-capacity-planning/28717#over-committing-resources-3).
    deprecated: "No"
  public-address:
    type: "string"
    default: "-"
    description: >-
      The public, reachable address of the node.
    deprecated: "No"
  subnet:
    type: "string"
    default: "-"
    description: >-
      The network subnet of the machine where the node runs.
    deprecated: "No"
  tags:
    type: "string"
    default: "-"
    description: >-
      Tags to identify the node.
    deprecated: "No"
  unschedulable:
    type: "bool"
    default: "false"
    description: >-
      If set to `true`, the node cannot be scheduled, which prevents
      new instances from being launched on it.
    deprecated: "No"
  agent.api.fingerprint:
    type: "string"
    default: "-"
    description: >-
      Fingerprint of certificate in the AMS trust store which is
      trusted when communicating with the stream agent.
    deprecated: "No"  
  agent.api.token:
    type: "string"
    default: "-"
    description: >-
      Token to be used for API authentication with stream agent.
    deprecated: "No"
  agent.api.url:
    type: "string"
    default: "-"
    description: >-
      URL for stream agent API endpoint.
    deprecated: "No"
